###
### GET request to example server
POST http://localhost:8000/api/join
Content-Type: application/json

{
  "user_name": "test_user9",
  "password": "password123"
}

### 로그인
POST http://localhost:8000/api/login
Content-Type: application/json

{
  "user_name": "test_user",
  "password": "password123"
}

### 프로파일
GET http://localhost:8000/api/profile
